### PR TITLE
updated readme to include installation instructions

### PR DESCRIPTION
**Pull request by finalcut**
added some basic installation instructions letting people know they have to clone the repo and where to clone it to.  I don't know to get the plugin included in the package manager install process but that would probably be a better solution in the long term.

I'm not sure what the conflict is; I just added a paragraph of text.

### CODE REVIEW

**Comment by finalcut** [comment]
I'm cleaning this one up and I'll let you know when it is done.

**Comment by adampresley** [comment]
The conflict is due to an edit I made earlier to the text. I'll look at merging it later. Also I did submit this to the Package Control repo but it was rejected because there is an older, more mature plugin for MXUnit. It was suggested I contribute to it instead.

**Comment by finalcut** [comment]
odd, I tried to get the older, more mature one from package manager in SublimeText3 and it wasn't listed as an option which is how I ended up finding yours.  Plus, yours appears to be more flexible so I'm glad I found it anyway.

**Comment by adampresley** [comment]
Yes, and it is because I use ST3 that I didn't notice it either, which is why I wrote this to begin with. I considered contributing to the other one, as it does have the cool results panel. I may yet. The biggest issue was I need additional arguments added to my test execution, as where I work for the day-job has some environment variables that are passed in via URL.

**Pull request merged**
